### PR TITLE
Improved CheckFileExists to make it faster

### PR DESCRIPTION
**Pull request by GabrielRavier**
Using `stat` instead of trying to `fopen` is 2.3 times faster

### CODE REVIEW

**Comment by Clownacy** [comment]
`stat` doesn't seem to be part of the C/C++ standard.

**Comment by GabrielRavier** [comment]
Does CSE2 have to be strictly compliant ? I myself know of no environment that implements the C standard but not `sys/stat.h`. I guess I'll make this conditional with something like `#if defined(__unix__) || defined(__unix) || (defined(__APPLE__) && defined(__MACH__)) || defined(_WIN32)`.

**Comment by Clownacy** [comment]
I'd prefer CSE2 to stick to the standards. I also don't want to add a bunch of platform-specific checks like that.

**Comment by GabrielRavier** [comment]
I mean, it does stick to the POSIX standard and works on anything that has any kind of support for any UNIX functions, but idk. Also, if you don't want to add platform-specific checks, I'm not exactly sure you'll like the proposed fix I just pushed.

**Comment by Clownacy** [comment]
I mean the C/C++ standards. If anything, I'd prefer to stick to a common subset of C99/C++98.

**Pull request closed without merging**
