### PR TITLE
Fixed a bunch of npc->cond = 0 bugs

### PR DESCRIPTION
**Pull request by GabrielRavier**

### CODE REVIEW

**Comment by Clownacy** [comment]
Could you make a sister PR to the accurate branch that notes these errors, [like what I did for the last set of fixes](https://github.com/Clownacy/Cave-Story-Engine-2/commit/a762f28837093b3972c3d26d94bbc2c71f96b27c)?

**Comment by GabrielRavier** [comment]
bruh

**Comment by Clownacy** [comment]
I think the `TSC_BUFFER_SIZE` stuff is less of a portability issue, and more of an engine limitation. I think it belongs in the enhanced branch more than anything.

**Comment by GabrielRavier** [comment]
Just removed that

**Pull request merged**
