### PR TITLE
Add support for <PHY

### PR DESCRIPTION
**Pull request by GabrielRavier**
Based on (https://github.com/taedixon/boosters-lab/blob/0fc60efe5f2339a41ecf171a07dd5fd3a921f7f7/hacks/TSC%20modifications/unobtrusive_phys_hack.xml)

### CODE REVIEW

**Comment by Clownacy** [comment]
Is there any way to clean up the commit history? Also the 'Files changed' tab is broken now for some reason, so it's hard to review the changes.

**Comment by GabrielRavier** [comment]
I'll try to do some magic with `git rebase`

**Comment by GabrielRavier** [comment]
Did a `git rebase enhanced` and force-pushed, the commit history should be fixed (I think the issue was because I had done a rebase then pulled instead of doing a force push)

**Comment by Clownacy** [comment]
What's blocking this for me right now is the need for ENABLE_PHY. Like with the other custom TSC command, I'd prefer a way that's backwards compatible with vanilla, with a compiler flag only needed to enable hacks for compatibility with existing mods.

**Comment by GabrielRavier** [comment]
I could probably just add a good default initializer to the array and that'd probably remove the need for ENABLE_PHY, now that I think about it...

**Comment by GabrielRavier** [comment]
This is still unfinished, I just pushed it so the Travis-CI check would prevent me about any problems in the merge

**Comment by GabrielRavier** [comment]
I've tested it in-game and the physics seem to work properly, so this probably is working properly

**Comment by Clownacy** [comment]
Awesome, thanks.

**Pull request merged**
