### PR TITLE
Check CMAKE_SYSTEM_NAME for not being Windows

### PR DESCRIPTION
**Pull request by GabrielRavier**
This solves numerous problems : 
- CMake could generate bogus files that wouldn't target Windows (and thus wouldn't build)
- CMake could generate an exe file without the .exe extension

### CODE REVIEW

**Comment by Clownacy** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/toolchain-mingw.cmake?h=mingw-w64-cmake

I don't see how this is CSE2's responsibility.

**Comment by GabrielRavier** [comment]
It's more useful for avoiding accidental bad usage of CMake than anything else, I use a toolchain file too now. I'd rather just have this and have people see an error as soon as possible instead of having them complain about "CSE2 not outputting a .exe" or things like that. I know we could also just put a note in the README, but people are more likely to notice a configuration error than a warning in a README (especially considering how easy it is to make it a configuration error)

**Comment by GabrielRavier** [comment]
I mean, possibly a more appropriate method would be to check for CMAKE_SYSTEM_NAME not being Windows and complaining then. Would that be a good idea ?

**Comment by GabrielRavier** [comment]
Just replaced it with that, does it LGTM ?

**Comment by Clownacy** [comment]
People trying to cross-compile should probably already know about these issues, since every other CMake project would be susceptible to them. I'd rather not start adding sanity checks for general CMake user-errors.

**Comment by GabrielRavier** [comment]
> People trying to cross-compile should probably already know about these issues, since every other CMake project would be susceptible to them

I mean, I had forgotten this issue, and I'm used to cross-compiling. It took me more than an hour and your help to diagnose why exactly this was happening and how to fix it (using `mingw64-cmake` instead of `cmake`).

Also, considering the accurate branch of CSE2 is specifically for Windows, I don't really see how such a sanity check would be extraneous.

**Comment by GabrielRavier** [comment]
Uh, really ? Is it that problematic to add 3 lines of code to prevent people from having to spend (like me) hours to find out why their build doesn't work properly, for something that is a supported build method ?

**Comment by Clownacy** [comment]
It's the precedent that it sets: it's three lines now, but why not check if `CC` contains the string `mingw`? Why not check if the MinGW lib folder is included in the library path?

**Comment by GabrielRavier** [comment]
That would be ridiculous. 

I think this check is appropriate simply because the project is intrinsically Windows-only, and thus building it for anything but that doesn't make sense. Really, this is why I wanted that to be set by the CMakeLists, but now I see that could be problematic, what with it potentially ending up with weird configurations that don't really work (which is why the warning message suggests having a properly setup toolchain file for Windows)

CSE2 accurate simply cannot be built properly without having Windows as the target, so that's why I think a check for that makes sense

**Comment by Clownacy** [comment]
It doesn't sound that farfetched to me: someone could do `CXX=i686-w64-mingw32-g++ cmake`, and get errors because they didn't set the correct `PKG_CONFIG_LIBDIR`. There are a whole bunch of sanity checks like that we could add, but I'd rather not because I think they're outside the scope of the project.

I really don't think it's our responsibility to check if the user is using CMake properly - it's their problem.

**Comment by GabrielRavier** [comment]
Fair enough.

**Pull request closed without merging**
