### PR TITLE
Add bugfix for incorrect comparisons of BOOL variables

### PR DESCRIPTION
**Pull request by GabrielRavier**
If we used `bool`, this would be correct (as `bool` can only be `true` or `false`) but `BOOL` is actually `int`, so any non-zero value is considered to be "true" so these could be set to some bogus value which `TRUE` would not match.

### CODE REVIEW

**Comment by Clownacy** [comment]
I don't get it. If those variables are only ever set to TRUE and FALSE, then those checks seem sane to me.

**Comment by GabrielRavier** [comment]
Yeah, I wanted to add this mostly because my static analyzer bugs me about it (it does this because some insane WinAPI functions return a BOOL which is neither FALSE nor TRUE)

**Comment by Clownacy** [comment]
I feel like this obscures the code's meaning, just to compensate for an edgecase that shouldn't even be possible.

**Comment by GabrielRavier** [comment]
I suppose the fix isn't exactly beautiful, yeah. Guess I'll be closing this

**Pull request closed without merging**
