### PR TITLE
Add better Makefile debug flags

### PR DESCRIPTION
**Pull request by GabrielRavier**
This changes the debug flags in the Makefile from `-O0 -g` to `-Og -g3` which provides more debugging information

### CODE REVIEW

**Comment by Clownacy** [comment]
I like -g3, but I don't get why -Og is needed. CSE2 isn't very demanding, and I'd rather have faster compile times when I'm debugging.

**Comment by GabrielRavier** [comment]
-Og adds some debugging information, since certain optimisation passes add debugging information (don't exactly remember how I'm looking up the gcc documentation)

**Comment by GabrielRavier** [comment]
Oh yeah here it is :

> '-Og'
     Optimize debugging experience.  '-Og' should be the optimization
     level of choice for the standard edit-compile-debug cycle, offering
     a reasonable level of optimization while maintaining fast
     compilation and a good debugging experience.  It is a better choice
     than '-O0' for producing debuggable code because some compiler
     passes that collect debug information are disabled at '-O0'.

**Comment by Clownacy** [comment]
Oh okay, cool.

**Pull request merged**
