### PR TITLE
Add "Creepy Curly" NPC 

### PR DESCRIPTION
**Pull request by GabrielRavier**
This also makes it so there is elemental support for CS+'s added NPCs
This adds NpcAct360.cpp (with stubs for CS+'s added NPCs) and NpcAct380.cpp (with the "Creepy Curly" NPC as NPC 381)

### CODE REVIEW

**Comment by Clownacy** [comment]
It doesn't look like you added the new .cpp files to the Makefile.

**Comment by GabrielRavier** [comment]
Yeah I forgot, just added them now

**Comment by GabrielRavier** [comment]
Also, you suggested [here](https://github.com/Clownacy/Cave-Story-Engine-2/pull/60#issuecomment-547099719) that Creepy Curly should be implemented in a vanilla-compatible way, with a flag that makes it overwrite NPC 161 (or whatever the original NPC is, I don't really remember). How do you suggest I go about implementing that flag ? Should it be done with some TSC command to activate stuff like you'd do with cmake policies ?

**Comment by Clownacy** [comment]
I was thinking more like a preprocessor definition, so you could build a CSE2 binary that's compatible with old mods, or you could make a binary that's compatible with vanilla, but still has the extra features.

**Comment by GabrielRavier** [comment]
Oh, ok. I'll add an ifdef to make it so the NPC Creepy Curly overrides redirects to Creepy Curly when set, then

**Comment by GabrielRavier** [comment]
Done

**Pull request merged**
