### PR TITLE
Add support for <MIM

### PR DESCRIPTION
**Pull request by GabrielRavier**
This adds support for the <MIM command, based on [BL's support for it](https://github.com/taedixon/boosters-lab/blob/master/hacks/TSC%20modifications/unobtrusive_infinite_mimigamask.xml) (except it doesn't use part of gFlagNPC to contain its variable)

### CODE REVIEW

**Comment by Clownacy** [comment]
Are you sure we should be hiding these behind `#ifdef`s? The ExtraMusicFormat stuff uses `#ifdef`s, because I find it a little heavyweight for something few people are going to use, and enabling certain formats imposes license obligations on the user, like how AUDIO_TRACKER pulls in the MIT-licensed libxmp-lite. These commits just add a few lines.

**Comment by GabrielRavier** [comment]
Some of the code straight up replaces other code. This wouldn't mean people would have to use a compile flag for each either ; We could just have a generic flag for all of those with code like this :
`#ifdef ENABLE_TSC_ADDITIONAL_COMMANDS`
`#define ENABLE_MIM`
`#define ENABLE_SOME_OTHER_COMMAND`
`#define ENABLE_MOAR_COMMANDS`
`#endif`

**Comment by Clownacy** [comment]
I don't see any code being replaced in the commits.

**Comment by GabrielRavier** [comment]
I meant the `#else` in one of the NPCs (code that is replaced in BL's hack)
If <MIM support is unconditional, that code is thus to be replaced

**Comment by Clownacy** [comment]
...Dammit how did I miss that.

Is there no way to make it compatible with the old Mimiga Mask behaviour?

**Comment by GabrielRavier** [comment]
Well, theorically you could just leave that code, but it could possibly make it uncompatible with existing mods

**Comment by Clownacy** [comment]
I feel like that might be an edgecase not worth worrying about. That'd require a mod to allow the player to obtain the mask, despite the old patch disabling its effect.

**Comment by GabrielRavier** [comment]
It could be possible to do so here, but I'm currently working on <PHY, and that seems to be much more complicated. I guess I can ignore this case, but I'm almost sure <PHY and more complicated commands will bring problems that can't just be ignored like this (and I'd like to keep consistency, too, so...)

**Comment by Clownacy** [comment]
Cross-posting this from the Discord server:

> I wonder. Maybe, instead of having stuff like <MIM be hidden behind #ifdefs because they break vanilla behaviour, we could implement them in a vanilla-compatible way, and then have #ifdefs for backwards-compatible hacks.
> 
> So Creepy Curly would have a flag to change its NPC number to overwrite that one vanilla NPC.
> 
> And <MIM would have a flag to completely nullify the Mimiga Mask's effects.
>

**Comment by GabrielRavier** [comment]
I think I did what you wanted there

**Pull request merged**
