### PR TITLE
Optimize images (ImgBot)

### PR DESCRIPTION
**Pull request by GabrielRavier**
Size of images went from 1,272.24kb to 1,097.97kb (a 13.7% reduction) apparently

It's lossless compression btw.

### CODE REVIEW

**Comment by Clownacy** [comment]
I'd rather not edit the libraries if I can help it. If I wanted to minimise their size, I'd remove their documentation altogether.

**Comment by GabrielRavier** [comment]
Should I try filtering out the changes to the libraries (and only keep changes to non-external files) ?

**Comment by Clownacy** [comment]
Sure.

**Comment by GabrielRavier** [comment]
I think I fixed it. Might also push some stuff so that imgbot just ignores those in the future btw.

**Pull request merged**
