### PR TITLE
Eliminate some identical case branches

### PR DESCRIPTION
**Pull request by GabrielRavier**
Pretty self-explanatory, but essentially this just removes a few `case` statements which were identical to other `case` statements

### CODE REVIEW

**Comment by Clownacy** [comment]
This breaks ASM-accuracy. The portable branch is only meant to change however much is necessary to make the game run on other platforms.

**Comment by GabrielRavier** [comment]
Ah, so this would go to enhanced then ? (I changed it to go to enhanced)

**Comment by Clownacy** [comment]
Sorry, but I don't want to add stylistic code changes to enhanced.

**Comment by GabrielRavier** [comment]
Ok.

**Pull request closed without merging**
